[package]
name = "cobweb-starter"
version = "0.1.0"
edition = "2024"

[lib]

[dependencies]
bevy = "0.16.1"
bevy_cobweb = "0.17.2"
bevy_cobweb_ui = { version = "0.21.0", features = [
    "hot_reload",
    "widgets",
    "colors",
] }
