[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = [
    # use the mold linker
    "-C",
    "link-arg=-fuse-ld=/usr/bin/mold",
    # (Nightly) Make the current crate share its generic instantiations
    "-Zshare-generics=y",
]
# use cranelift; new nightly-only codegen that is about 30% faster
[unstable]
codegen-backend = true

[profile.dev]
codegen-backend = "cranelift"

[profile.dev.package."*"]
codegen-backend = "llvm"
